/**
 * 合句：把相邻原始字幕片段组成可读的句子单元，保留 parts 映射。
 *
 * 规则：
 * 1. 输入先防御性清洗（非法时间/空文本丢弃）、排序，相同起点合并；
 * 2. 片段内部若有明确句末（「Thanks. Now…」），按字符比例插值时间拆分，使每句有自己的起止时间；
 * 3. 依次累积，遇到句末标点、停顿超过 gapBreakMs、字符/时长超限、或长句中的从句标点时断句；
 *    自动字幕通常无标点，主要依靠停顿与长度；
 * 4. 输出单元 startMs 严格递增，endMs 不晚于下一单元 startMs；id = 前缀 + 起始毫秒，稳定可复现。
 */
import {
  MAX_CUE_TEXT_LENGTH,
  MAX_MEDIA_TIME_MS,
  type Cue,
  type RawCaptionCue,
} from '../domain/cue';
import type { BuildCueUnits, BuildUnitsOptions } from './types';
import {
  endsClause,
  endsSentence,
  joinCaptionText,
  normalizeCaptionText,
  stableIdPrefix,
  truncateText,
} from './text';

export const MANUAL_UNIT_DEFAULTS = {
  maxUnitDurationMs: 10_000,
  maxUnitChars: 220,
  gapBreakMs: 1_500,
} as const;
export const AUTO_UNIT_DEFAULTS = {
  maxUnitDurationMs: 7_000,
  maxUnitChars: 140,
  gapBreakMs: 800,
} as const;
const MAX_PARTS = 200;
/** 片段内拆句时，每侧至少保留的时长。 */
const MIN_SPLIT_SIDE_MS = 200;

interface Piece {
  startMs: number;
  endMs: number;
  text: string;
}

/** 片段内部的句末拆分位置（返回拆分后的文本段）。 */
export function splitSentences(text: string): string[] {
  const out: string[] = [];
  let rest = text;
  // 句末标点 + 可选闭合引号；拉丁标点后需空白且下一个字符像句首，中日文标点后直接拆。
  const re = /([.!?。！？‼⁉]["'”’）)\]」』]*)(\s*)(?=\S)/g;
  let guard = 0;
  while (rest && guard++ < 50) {
    re.lastIndex = 0;
    let splitAt = -1;
    let m: RegExpExecArray | null;
    while ((m = re.exec(rest))) {
      const punctEnd = m.index + m[1]!.length;
      const left = rest.slice(0, punctEnd);
      const nextChar = rest[punctEnd + m[2]!.length] ?? '';
      const isCjkPunct = /[。！？‼⁉]/.test(m[1]![0]!);
      const hasSpace = m[2]!.length > 0;
      const looksLikeStart = /[\p{Lu}\p{N}"'“‘([¿¡]|[^\p{Script=Latin}\p{P}\s]/u.test(nextChar);
      if (
        (isCjkPunct || (hasSpace && looksLikeStart)) &&
        endsSentence(left) &&
        left.trim().length >= 2
      ) {
        splitAt = punctEnd;
        break;
      }
    }
    if (splitAt < 0) break;
    const left = rest.slice(0, splitAt).trim();
    const right = rest.slice(splitAt).trim();
    if (!left || right.length < 2) break;
    out.push(left);
    rest = right;
  }
  if (rest.trim()) out.push(rest.trim());
  return out;
}

function toPieces(raw: RawCaptionCue): Piece[] {
  const segments = splitSentences(raw.text);
  if (segments.length <= 1) return [{ startMs: raw.startMs, endMs: raw.endMs, text: raw.text }];
  const duration = raw.endMs - raw.startMs;
  if (duration < MIN_SPLIT_SIDE_MS * segments.length)
    return [{ startMs: raw.startMs, endMs: raw.endMs, text: raw.text }];
  const total = segments.reduce((n, s) => n + s.length, 0);
  const pieces: Piece[] = [];
  let acc = 0;
  let prevBoundary = raw.startMs;
  for (let i = 0; i < segments.length; i++) {
    acc += segments[i]!.length;
    const isLast = i === segments.length - 1;
    let boundary = isLast ? raw.endMs : Math.round(raw.startMs + (duration * acc) / total);
    // 每侧至少 MIN_SPLIT_SIDE_MS，保证起点严格递增。
    boundary = Math.max(boundary, prevBoundary + MIN_SPLIT_SIDE_MS);
    if (!isLast)
      boundary = Math.min(boundary, raw.endMs - MIN_SPLIT_SIDE_MS * (segments.length - 1 - i));
    pieces.push({ startMs: prevBoundary, endMs: boundary, text: segments[i]! });
    prevBoundary = boundary;
  }
  return pieces;
}

function sanitizeRaw(raw: readonly RawCaptionCue[]): RawCaptionCue[] {
  const valid: RawCaptionCue[] = [];
  for (const c of raw) {
    if (!c || !Number.isFinite(c.startMs) || !Number.isFinite(c.endMs)) continue;
    if (c.startMs < 0 || c.startMs >= MAX_MEDIA_TIME_MS) continue;
    const text = normalizeCaptionText(typeof c.text === 'string' ? c.text : '');
    if (!text) continue;
    const startMs = Math.round(c.startMs);
    const endMs = Math.min(MAX_MEDIA_TIME_MS, Math.max(Math.round(c.endMs), startMs + 1));
    valid.push({ startMs, endMs, text: truncateText(text, MAX_CUE_TEXT_LENGTH).text });
  }
  valid.sort((a, b) => a.startMs - b.startMs);
  const merged: RawCaptionCue[] = [];
  for (const c of valid) {
    const last = merged[merged.length - 1];
    if (last && last.startMs === c.startMs) {
      if (last.text !== c.text)
        last.text = truncateText(joinCaptionText(last.text, c.text), MAX_CUE_TEXT_LENGTH).text;
      last.endMs = Math.max(last.endMs, c.endMs);
    } else {
      merged.push({ ...c });
    }
  }
  return merged;
}

export function makeCueId(prefix: string, startMs: number, used: Set<string>): string {
  const base = `${stableIdPrefix(prefix)}:${startMs}`;
  let id = base;
  for (let n = 1; used.has(id); n++) id = `${base}.${n}`;
  used.add(id);
  return id;
}

export const buildCueUnits: BuildCueUnits = (raw, options: BuildUnitsOptions) => {
  const defaults = options.autoGenerated ? AUTO_UNIT_DEFAULTS : MANUAL_UNIT_DEFAULTS;
  const maxDur = options.maxUnitDurationMs ?? defaults.maxUnitDurationMs;
  const maxChars = options.maxUnitChars ?? defaults.maxUnitChars;
  const gapBreak = options.gapBreakMs ?? defaults.gapBreakMs;

  // 输入片段可能互相重叠：拆句后再次排序并合并相同起点，保证单元起点严格递增。
  const pieces: Piece[] = [];
  for (const p of sanitizeRaw(raw)
    .flatMap(toPieces)
    .sort((a, b) => a.startMs - b.startMs)) {
    const last = pieces[pieces.length - 1];
    if (last && last.startMs === p.startMs) {
      last.text = joinCaptionText(last.text, p.text);
      last.endMs = Math.max(last.endMs, p.endMs);
    } else {
      pieces.push({ ...p });
    }
  }

  interface Unit {
    startMs: number;
    endMs: number;
    lastEndMs: number;
    text: string;
    parts: Array<{ startMs: number; endMs: number }>;
  }
  const units: Unit[] = [];
  let cur: Unit | undefined;

  for (const p of pieces) {
    if (cur) {
      const gap = p.startMs - cur.lastEndMs;
      const projectedText = joinCaptionText(cur.text, p.text);
      const curDur = cur.lastEndMs - cur.startMs;
      const shouldBreak =
        gap > gapBreak ||
        endsSentence(cur.text) ||
        projectedText.length > maxChars ||
        p.endMs - cur.startMs > maxDur ||
        cur.parts.length >= MAX_PARTS ||
        (endsClause(cur.text) && (cur.text.length >= maxChars * 0.5 || curDur >= maxDur * 0.5));
      if (!shouldBreak) {
        cur.text = projectedText;
        cur.endMs = Math.max(cur.endMs, p.endMs);
        cur.lastEndMs = p.endMs;
        cur.parts.push({ startMs: p.startMs, endMs: p.endMs });
        continue;
      }
      units.push(cur);
    }
    cur = {
      startMs: p.startMs,
      endMs: p.endMs,
      lastEndMs: p.endMs,
      text: p.text,
      parts: [{ startMs: p.startMs, endMs: p.endMs }],
    };
  }
  if (cur) units.push(cur);

  const used = new Set<string>();
  const out: Cue[] = [];
  for (let i = 0; i < units.length; i++) {
    const u = units[i]!;
    const next = units[i + 1];
    let endMs = u.endMs;
    // 时间单调：不与下一单元重叠。
    if (next && endMs > next.startMs) endMs = next.startMs;
    if (endMs <= u.startMs) endMs = u.startMs + 1;
    out.push({
      id: makeCueId(options.idPrefix, u.startMs, used),
      revision: 0,
      startMs: u.startMs,
      endMs,
      sourceText: truncateText(u.text, MAX_CUE_TEXT_LENGTH * 4).text,
      sourceLanguage: options.sourceLanguage || 'und',
      targetLanguage: options.targetLanguage,
      source: options.source,
      stability: 'final',
      translationState: 'pending',
      parts: u.parts.map((p) => ({
        startMs: p.startMs,
        endMs: Math.min(p.endMs, MAX_MEDIA_TIME_MS),
      })),
    });
  }
  return out;
};
