/**
 * 字幕规范化与合句契约（纯函数/纯状态，可在 worker 与内容脚本中复用）。
 */
import type { Cue, RawCaptionCue } from '../domain/cue';

export interface BuildUnitsOptions {
  /** 源轨道语言（'und' 表示未知）。 */
  sourceLanguage: string;
  targetLanguage: string;
  /** 用于生成稳定 cue id 的来源前缀，例如 `${videoId}:${trackKey}`。 */
  idPrefix: string;
  source: 'caption-track';
  /** 自动字幕通常没有标点，使用停顿与长度切句。 */
  autoGenerated: boolean;
  maxUnitDurationMs?: number;
  maxUnitChars?: number;
  /** 相邻片段间隔超过该值则断句。 */
  gapBreakMs?: number;
}

/** 将原始字幕片段合成可读句子单元，并保留 parts 映射；输出按 startMs 升序、时间单调。 */
export type BuildCueUnits = (raw: readonly RawCaptionCue[], options: BuildUnitsOptions) => Cue[];

/**
 * 仅能读取当前显示字幕时的增量组装器：处理滚动字幕的重复文本、逐词变化，
 * 以临时 cue（interim）发出，稳定后以 final 发出。
 */
export interface IncrementalCaptionAssembler {
  push(sample: { text: string; mediaTimeMs: number }): { upserts: Cue[]; removedIds: string[] };
  /** 跳转/暂停等断点：结束当前临时句。 */
  flush(mediaTimeMs: number): { upserts: Cue[]; removedIds: string[] };
  reset(): void;
}

/** ASR 分段结果 → cue：按时间与文本去重重叠段，修订使用 revision。 */
export interface AsrCueAssembler {
  push(result: {
    segmentId: string;
    startMs: number;
    endMs: number;
    endEstimated: boolean;
    text: string;
    language?: string;
    final: boolean;
    revision: number;
  }): { upserts: Cue[]; removedIds: string[] };
  reset(): void;
}
