import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { CueSchema, findActiveCue, type Cue, type RawCaptionCue } from '@src/domain/cue';
import { buildCueUnits, splitSentences } from '@src/captions/build-units';
import { parseJson3, parseVtt } from '@src/captions/parse';
import type { BuildUnitsOptions } from '@src/captions/types';

const fixture = (name: string) =>
  readFileSync(resolve(import.meta.dirname, '../../fixtures/youtube', name), 'utf8');

const base: BuildUnitsOptions = {
  sourceLanguage: 'en',
  targetLanguage: 'zh-CN',
  idPrefix: 'abcdefghijk:.en',
  source: 'caption-track',
  autoGenerated: false,
};

function expectMonotonic(units: Cue[]) {
  const ids = new Set<string>();
  for (let i = 0; i < units.length; i++) {
    const u = units[i]!;
    expect(CueSchema.safeParse(u).success).toBe(true);
    expect(ids.has(u.id)).toBe(false);
    ids.add(u.id);
    expect(u.endMs).toBeGreaterThan(u.startMs);
    const next = units[i + 1];
    if (next) {
      expect(next.startMs).toBeGreaterThan(u.startMs);
      expect(u.endMs).toBeLessThanOrEqual(next.startMs);
    }
    for (const p of u.parts ?? []) {
      expect(p.startMs).toBeGreaterThanOrEqual(u.startMs);
    }
  }
}

describe('splitSentences', () => {
  it('splits at sentence ends but not abbreviations, initials, decimals or ellipses', () => {
    expect(splitSentences('Thanks. Now we start.')).toEqual(['Thanks.', 'Now we start.']);
    expect(splitSentences('Mr. Smith paid $5.99 today.')).toEqual(['Mr. Smith paid $5.99 today.']);
    expect(splitSentences('J. R. R. Tolkien wrote it.')).toEqual(['J. R. R. Tolkien wrote it.']);
    expect(splitSentences('Wait... What happened?')).toEqual(['Wait... What happened?']);
    expect(splitSentences('it is fine. and lowercase continues')).toEqual([
      'it is fine. and lowercase continues',
    ]);
    expect(splitSentences('你好。我们开始吧！好的')).toEqual(['你好。', '我们开始吧！', '好的']);
  });
});

describe('buildCueUnits', () => {
  it('merges manual caption fragments into sentences with parts mapping and stable ids', () => {
    const raw = parseJson3(fixture('manual.json3')).cues;
    const units = buildCueUnits(raw, base);
    expectMonotonic(units);
    const welcome = units[0]!;
    expect(welcome.sourceText).toBe('Welcome to the channel, everyone.');
    expect(welcome.parts).toEqual([
      { startMs: 1000, endMs: 3500 },
      { startMs: 3500, endMs: 5500 },
    ]);
    expect(welcome).toMatchObject({
      id: 'abcdefghijk:.en:1000',
      revision: 0,
      startMs: 1000,
      endMs: 5500,
      sourceLanguage: 'en',
      targetLanguage: 'zh-CN',
      source: 'caption-track',
      stability: 'final',
      translationState: 'pending',
    });
    // 同一输入重建得到相同 id。
    expect(buildCueUnits(raw, base).map((u) => u.id)).toEqual(units.map((u) => u.id));
    // HTML 样式文本保持为字面字符串。
    expect(units.some((u) => u.sourceText.includes('<img src=x onerror=alert(1)>'))).toBe(true);
  });

  it('splits a fragment containing two sentences and gives each its own interpolated time', () => {
    const raw: RawCaptionCue[] = [
      { startMs: 9000, endMs: 12000, text: "It costs $5.99. That's not cheap." },
    ];
    const units = buildCueUnits(raw, base);
    expectMonotonic(units);
    expect(units.map((u) => u.sourceText)).toEqual(['It costs $5.99.', "That's not cheap."]);
    expect(units[0]!.startMs).toBe(9000);
    expect(units[1]!.startMs).toBeGreaterThan(9000);
    expect(units[1]!.startMs).toBeLessThan(12000);
    expect(units[1]!.endMs).toBe(12000);
    expect(findActiveCue(units, 11_500)?.sourceText).toBe("That's not cheap.");
  });

  it('breaks auto captions without punctuation by pause and duration', () => {
    const raw = parseJson3(fixture('auto.json3')).cues;
    const units = buildCueUnits(raw, {
      ...base,
      autoGenerated: true,
      idPrefix: 'abcdefghijk:a.en',
    });
    expectMonotonic(units);
    expect(units.map((u) => u.sourceText)).toEqual([
      'so today we are going to talk about captions',
      'and how they work',
      "first let's look at the player",
    ]);
    expect(units.map((u) => [u.startMs, u.endMs])).toEqual([
      [400, 5200],
      [5200, 8200],
      [10200, 13400],
    ]);
  });

  it('produces the same units from vtt rolling captions without duplicated text', () => {
    const units = buildCueUnits(parseVtt(fixture('auto.vtt')).cues, {
      ...base,
      autoGenerated: true,
    });
    const text = units.map((u) => u.sourceText).join(' ');
    expect(text).toBe(
      "so today we are going to talk about captions and how they work first let's look at the player",
    );
    expectMonotonic(units);
  });

  it('respects maxUnitChars, gapBreakMs and clause breaks', () => {
    const raw: RawCaptionCue[] = Array.from({ length: 10 }, (_, i) => ({
      startMs: i * 1000,
      endMs: i * 1000 + 1000,
      text: `word${i} another`,
    }));
    const units = buildCueUnits(raw, { ...base, maxUnitChars: 40, maxUnitDurationMs: 60_000 });
    expectMonotonic(units);
    for (const u of units) expect(u.sourceText.length).toBeLessThanOrEqual(40);
    const gapUnits = buildCueUnits(
      [
        { startMs: 0, endMs: 1000, text: 'before the pause' },
        { startMs: 5000, endMs: 6000, text: 'after the pause' },
      ],
      base,
    );
    expect(gapUnits).toHaveLength(2);
  });

  it('handles unsorted, overlapping, same-start, invalid and empty input defensively', () => {
    const raw = [
      { startMs: 5000, endMs: 9000, text: 'later sentence.' },
      { startMs: 0, endMs: 6000, text: 'first sentence.' },
      { startMs: 0, endMs: 2000, text: 'same start.' },
      { startMs: -1, endMs: 10, text: 'negative' },
      { startMs: Number.NaN, endMs: 10, text: 'nan' },
      { startMs: 7000, endMs: 7000, text: '   ' },
    ] as RawCaptionCue[];
    const units = buildCueUnits(raw, base);
    expectMonotonic(units);
    expect(units.map((u) => u.sourceText)).toEqual([
      'first sentence. same start.',
      'later sentence.',
    ]);
    expect(units[0]!.endMs).toBe(5000);
    expect(buildCueUnits([], base)).toEqual([]);
  });

  it('keeps ids within 120 chars for long prefixes', () => {
    const units = buildCueUnits([{ startMs: 1, endMs: 2, text: 'x' }], {
      ...base,
      idPrefix: 'p'.repeat(300),
    });
    expect(units[0]!.id.length).toBeLessThanOrEqual(120);
    expect(CueSchema.safeParse(units[0]).success).toBe(true);
  });

  it('keeps timing monotonic with many tiny fragments and CJK text', () => {
    const raw: RawCaptionCue[] = [];
    for (let i = 0; i < 500; i++)
      raw.push({ startMs: i * 37, endMs: i * 37 + 50, text: i % 7 === 0 ? '文です。' : '字幕' });
    const units = buildCueUnits(raw, { ...base, sourceLanguage: 'ja' });
    expectMonotonic(units);
    expect(units.every((u) => !u.sourceText.includes(' '))).toBe(true);
  });
});
